on: push
name: Bicep deploy

jobs:
  resource_groups:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@main
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy resource groups
      id: resourcegroups
      uses: azure/arm-deploy@v1
      with:
        template: ./infra/resource_groups/main.bicep
        scope: subscription
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        region: westeurope
    outputs:
      registryRGName: ${{ steps.resourcegroups.outputs.registryRGName }}
      ctnrAppRgName: ${{ steps.resourcegroups.outputs.ctnrAppRgName }}

  service_principal:
    needs: resource_groups
    runs-on: ubuntu-20.04
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: |
        sudo apt update
        sudo apt install -y jq
    - run: |
        az ad sp create-for-rbac
        --name "myApp"
        --role contributor
        --scopes /subscriptions/${{ secrets.AZ_SUBSCRIPTION_ID_DEV }}/resourceGroups/${{ needs.resource_groups.outputs.registryRGName }}
        --sdk-auth > client.json
        jq -r '.clientId' client.json | gh secret set AZ_SP_CLIENT_ID
        jq -r '.clientSecret' client.json | gh secret set AZ_SP_CLIENT_SECRET      

  build_and_deploy:
    needs: resource_groups
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@main
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy container registry
      id: registry
      uses: azure/arm-deploy@v1
      with:
        template: ./infra/registry/main.bicep
        scope: resourcegroup
        resourceGroupName: ${{ needs.resource_groups.outputs.registryRGName }}
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        region: westeurope

    - name: Build image
      id: acr
      uses: azure/acr-build@v1
      with:
        service_principal: ${{ secrets.AZ_SP_CLIENT_ID }}
        service_principal_password: ${{ secrets.AZ_SP_CLIENT_SECRET }}
        tenant: ${{ secrets.TENANT }}
        registry: ${{ steps.registry.outputs.registryName }}
        repository: server
        image: dev
        tag: ${{ github.sha }}
        git_access_token: ${{ secrets.GIT_ACCESS_TOKEN }}
        branch: main

    - name: Deploy infrastructure
      uses: azure/arm-deploy@v1
      with:
        template: ./infra/main.bicep
        scope: resourcegroup
        resourceGroupName: ${{ needs.resource_groups.outputs.ctnrAppRgName }}
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        region: westeurope
        failOnStdErr: true
        parameters: >
          tag=${{ github.sha }}
          registryName=${{ steps.registry.outputs.registryName }}
          registryResourceGroup=${{ needs.resource_groups.outputs.registryRGName }}
          subscriptionId=${{ secrets.AZURE_SUBSCRIPTION }}
