on: push
name: Bicep deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@main
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Container Registry
      id: registry
      uses: azure/arm-deploy@v1
      with:
        template: ./infra/registry/main.bicep
        scope: subscription
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        region: westeurope

    - name: Docker Build and Push
      run: |
        az acr login --name ${{ steps.registry.outputs.registryName }}
        TAG=${{ github.sha }}
        docker build -t ${{ steps.registry.outputs.loginServer }}:$TAG .
        docker push ${{ steps.registry.outputs.loginServer }}:$TAG

    # - name: Deploy Bicep files
    #   uses: azure/arm-deploy@v1
    #   with:
    #     template: ./infra/main.bicep
    #     scope: subscription
    #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
    #     region: westeurope
    #     failOnStdErr: true
    #     parameters: registryName=${{ steps.registry.outputs.registryName }} registryResourceGroup=${{ steps.registry.outputs.resourceGroupName }} loginServer=${{ steps.registry.outputs.loginServer }} subscriptionId=${{ secrets.AZURE_SUBSCRIPTION }}
