on: push
name: Bicep deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@main
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Container Registry
      id: registry
      uses: azure/arm-deploy@v1
      with:
        template: ./infra/registry/main.bicep
        scope: subscription
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        region: westeurope

    - run: echo ${{ steps.registry.outputs.registryName }}

    # login to acr
    # docker tag
    # docker push

    # - name: Deploy Bicep files
    #   uses: azure/arm-deploy@v1
    #   with:
    #     template: ./infra/main.bicep
    #     scope: subscription
    #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
    #     region: westeurope
    #     failOnStdErr: true
    #     parameters: ${{ steps.registry.outputs.registryName }}
